<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Rig.TUnit.Core\Rig.TUnit.Core.csproj" />
    <ProjectReference Include="..\Rig.TUnit.Grpc\Rig.TUnit.Grpc.csproj" />
    <ProjectReference Include="..\Rig.TUnit.SqlServer\Rig.TUnit.SqlServer.csproj" />
    <ProjectReference Include="..\Rig.TUnit.Redis\Rig.TUnit.Redis.csproj" />
    <ProjectReference Include="..\Rig.TUnit.ServiceBus\Rig.TUnit.ServiceBus.csproj" />
  </ItemGroup>
</Project>
