<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="KurrentDB.Client" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rig.TUnit.Databases.NoSql.KurrentDb\Rig.TUnit.Databases.NoSql.KurrentDb.csproj" />
  </ItemGroup>
</Project>
