<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseAspNetCore>true</UseAspNetCore>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rig.TUnit.Security\Rig.TUnit.Security.csproj" />
    <ProjectReference Include="..\Rig.TUnit.Security.Jwt\Rig.TUnit.Security.Jwt.csproj" />
  </ItemGroup>
</Project>
