<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TUnit.AspNetCore" Version="1.34.5" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rig.TUnit.Core\Rig.TUnit.Core.csproj" />
    <ProjectReference Include="..\Rig.TUnit.Mediator\Rig.TUnit.Mediator.csproj" />
  </ItemGroup>
</Project>
