<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="Testcontainers.Minio" />
    <PackageReference Include="Minio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rig.TUnit.Storage\Rig.TUnit.Storage.csproj" />
  </ItemGroup>
</Project>
