<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="Testcontainers.KurrentDb" />
    <PackageReference Include="KurrentDB.Client" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rig.TUnit.Databases.NoSql\Rig.TUnit.Databases.NoSql.csproj" />
  </ItemGroup>
</Project>
