<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="Testcontainers.Nats" />
    <PackageReference Include="NATS.Client.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rig.TUnit.Messaging\Rig.TUnit.Messaging.csproj" />
  </ItemGroup>
</Project>
