<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="Testcontainers.EventStoreDb" />
    <PackageReference Include="EventStore.Client.Grpc.Streams" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rig.TUnit.Databases.NoSql\Rig.TUnit.Databases.NoSql.csproj" />
  </ItemGroup>
</Project>
