<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
  </ItemGroup>
  <ItemGroup>
    <None Update="TestInfrastructure/service-bus-config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rig.TUnit.Messaging.ServiceBus\Rig.TUnit.Messaging.ServiceBus.csproj" />
    <ProjectReference Include="..\Rig.TUnit.Messaging.Tests.Contract\Rig.TUnit.Messaging.Tests.Contract.csproj" />
    <ProjectReference Include="..\Rig.TUnit.Parallelism.Tests.Contract\Rig.TUnit.Parallelism.Tests.Contract.csproj" />
  </ItemGroup>
</Project>
