<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="AWSSDK.DynamoDBv2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rig.TUnit.Databases.NoSql.Dynamo\Rig.TUnit.Databases.NoSql.Dynamo.csproj" />
  </ItemGroup>
</Project>
