<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Rig.TUnit.Core\Rig.TUnit.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="coverage-whitelist.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
